### ISSUE TITLE
How to proxy HTTPS?

### ISSUE THREAD

**Issue by TheGP** [apify/proxy-chain#537]
While opening website in a browser (connected to proxy-chain) looks like connect requests skip prepareRequestFunction completely and not redirected to proxy, why? I want to proxy everything.

**Comment by jancurn** [comment]
HTTPS is proxied using so-called HTTP CONNECT tunnel and the `prepareRequestFunction` function is called once when this tunnel opens. The problem is that web browser typically reuse HTTPS connections to the website for multiple requests, which is transparent to the proxy due to encryption, so the `prepareRequestFunction` is not called again. You'll need to restart the browser or force it somehow not to reuse HTTPS connections.

**Comment by TheGP** [comment]
You just copied it from docs. I don't want to decrypt https, i want proxy to act at TCP redirect

**Comment by jancurn** [comment]
I wrote it. The problem is the browser, it just opens one socket for multiple requests. To control the requests, you need to make the browser open new sockets for each request. There's nothing the proxy can do about it.

**Comment by TheGP** [comment]
@jancurn my apologies I re-read it and removed before you answered. How does HTTP proxy work then? So the proxy should keep connections open then.

**Comment by jancurn** [comment]
Proxy just proxies sockets, but has not idea what data is running in them. That's what the web browser and the web server control.

**Comment by TheGP** [comment]
Yes thats what I want.
